/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spacetravel;

import spacetravel.client.Client;
import spacetravel.client.ClientCrudService;
import spacetravel.database_flyway_service.DatabaseFlyWayService;
import spacetravel.exception.NullOutputException;
import spacetravel.planet.Planet;
import spacetravel.planet.PlanetCrudService;
import spacetravel.ticket.TicketCrudService;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, NullOutputException {

        new DatabaseFlyWayService().initFlyWayDB();

        ClientCrudService clientCrudService = new ClientCrudService();

        Client client = new Client();
        client.setName("Tonks");
        clientCrudService.createNewClient(client);
        clientCrudService.deleteClient(client);

        PlanetCrudService planetCrudService = new PlanetCrudService();
        Planet planet = new Planet();
        planet.setId("SAT");
        planet.setName("Saturn");
        planetCrudService.createNewPlanet(planet);
        planetCrudService.deletePlanet(planet);


    }
}
